# Generated by Django 6.0.4 on 2026-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner / Supper'), ('anytime', 'Anytime')], max_length=20)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prep_time', models.CharField(default='30 mins', max_length=50)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
