# Generated by Django 6.0.4 on 2026-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', upload_to='dish_images/'),
            preserve_default=False,
        ),
    ]
