# Generated by Django 6.0.4 on 2026-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='best_with_drinks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='best_with_foods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Low'), ('low-mid', 'Low-Mid'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_dry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=10),
        ),
    ]
