# Generated by Django 6.0.4 on 2026-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dish_best_with_drinks_dish_best_with_foods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
