# Generated by Django 6.0.4 on 2026-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dish_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Low'), ('low-mid', 'Low-Mid'), ('mid', 'Mid'), ('high', 'High'), ('mid-high', 'Mid-High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
