# Generated by Django 6.0.4 on 2026-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dish_budget_level_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='food_role',
            field=models.JSONField(default=list),
        ),
    ]
