# Generated by Django 6.0.4 on 2026-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_food_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('high-protein', 'High Protein'), ('complex-carbs', 'Complex Carbs'), ('fruits', 'Fruits'), ('healthy-fats', 'Healthy Fats'), ('low-calorie', 'Low Calorie'), ('gym-snacks', 'Gym Snacks')], max_length=50)),
                ('food_type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('snack', 'Snack')], default='food', max_length=20)),
                ('timing', models.CharField(choices=[('pre-workout', 'Pre-Workout'), ('during-workout', 'During Workout'), ('post-workout', 'Post-Workout')], default='pre-workout', max_length=20)),
                ('timing_detail', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(help_text='One benefit per line')),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym_foods/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
