# Generated by Django 6.0.4 on 2026-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gymfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe_steps',
            field=models.TextField(blank=True, help_text='Write cooking steps, one per line. e.g:\n1. Boil water\n2. Add pasta', null=True),
        ),
    ]
