# Generated by Django 6.0.4 on 2026-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dish_recipe_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComradeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('staple', 'Staple'), ('protein', 'Protein'), ('vegetable', 'Vegetable'), ('spice', 'Spice/Seasoning'), ('snack', 'Quick Snack'), ('drink', 'Drink')], max_length=20)),
                ('price_ksh', models.IntegerField(help_text='Price in Kenyan Shillings')),
                ('unit', models.CharField(help_text='e.g. per packet, per kg, per piece', max_length=100)),
                ('ingredients_needed', models.TextField(blank=True, help_text='Comma-separated ingredients needed to cook this')),
                ('can_combine_with', models.TextField(blank=True, help_text='Comma-separated foods this goes well with')),
                ('cooking_tip', models.TextField(blank=True, help_text="Budget cooking tip e.g. 'Boil with salt for fastest meal'")),
                ('upgrade_tip', models.TextField(blank=True, help_text='How to upgrade if they have more ingredients')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comrade_foods/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComradeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_cost_ksh', models.IntegerField()),
                ('items', models.JSONField(help_text='List of {"item": "Indomie", "cost": 45, "qty": "1 packet"}')),
                ('kitchen_items_needed', models.TextField(blank=True, help_text='Comma-separated items you need from kitchen e.g. cooking oil, salt')),
                ('steps', models.TextField(blank=True, help_text='One cooking step per line')),
                ('upgrade_with', models.TextField(blank=True, help_text='e.g. Add onions+tomatoes if you have them')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comrade_meals/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags e.g. fastest,vegetarian,filling', max_length=200)),
            ],
        ),
    ]
