# Generated by Django 6.0.4 on 2026-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comradefood_comrademeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comradefood',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
