# Generated by Django 6.0.4 on 2026-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comradefood_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comrademeal',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
