# Generated by Django 6.0.4 on 2026-04-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comrademeal_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comrademeal',
            name='cooking_tip',
            field=models.TextField(blank=True, help_text="Quick cooking tip e.g. 'Boil with salt for fastest meal'"),
        ),
        migrations.AlterField(
            model_name='comrademeal',
            name='kitchen_items_needed',
            field=models.TextField(blank=True, help_text='Comma-separated items from kitchen e.g. cooking oil, salt'),
        ),
    ]
