# Generated by Django 6.0.4 on 2026-05-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comrademeal_cooking_tip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('fish', 'Fish'), ('greens', 'Greens / Vegetables'), ('legumes', 'Legumes / Beans'), ('egg', 'Egg'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stew_options/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stew_options', to='core.dish')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
