# Generated by Django 6.0.4 on 2026-05-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stewoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='stewoption',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Low'), ('low-mid', 'Low-Mid'), ('mid', 'Mid'), ('high', 'High'), ('mid-high', 'Mid-High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='stewoption',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
