# Generated by Django 6.0.4 on 2026-05-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stewoption_budget_level_stewoption_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stewoption',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stewoption',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma-separated list of ingredients'),
        ),
        migrations.AddField(
            model_name='stewoption',
            name='recipe_steps',
            field=models.TextField(blank=True, help_text='One step per line', null=True),
        ),
    ]
