# Generated by Django 6.0.4 on 2026-05-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stewoption_add_ons_stewoption_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StewOption',
            new_name='DishStewOption',
        ),
        migrations.AlterField(
            model_name='comradefood',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner / Supper'), ('anytime', 'Anytime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe_steps',
            field=models.TextField(blank=True, help_text='Write cooking steps, one per line.', null=True),
        ),
        migrations.CreateModel(
            name='ComradeFoodStewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('fish', 'Fish'), ('greens', 'Greens / Vegetables'), ('legumes', 'Legumes / Beans'), ('egg', 'Egg'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('low-mid', 'Low-Mid'), ('mid', 'Mid'), ('high', 'High'), ('mid-high', 'Mid-High')], default='low', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stew_options/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('ingredients', models.TextField(blank=True, help_text='Comma-separated list of ingredients')),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('recipe_steps', models.TextField(blank=True, help_text='One step per line', null=True)),
                ('comrade_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stew_options', to='core.comradefood')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
