# Generated by Django 6.0.4 on 2026-05-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_stewoption_dishstewoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comrademeal',
            name='comrade_food',
            field=models.ForeignKey(blank=True, help_text='Link to the base ComradeFood item (e.g. Rice) to show Eat With stew options', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='core.comradefood'),
        ),
    ]
