# Generated by Django 6.0.4 on 2026-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comrademeal_comrade_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymfood',
            name='purpose',
            field=models.CharField(choices=[('weight-loss', 'Ideal for Weight Loss'), ('weight-gain', 'Ideal for Weight Gain'), ('muscle-build', 'Builds Muscle'), ('endurance', 'Boosts Endurance'), ('recovery', 'Aids Recovery'), ('general', 'General Fitness')], default='general', help_text='What is this food ideal for?', max_length=50),
        ),
    ]
