# Generated by Django 6.0.4 on 2026-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_gymfood_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymfood',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
