# Generated by Django 6.0.4 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_gymfood_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymfood',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma-separated list of ingredients'),
        ),
        migrations.AddField(
            model_name='gymfood',
            name='recipe_steps',
            field=models.TextField(blank=True, help_text='One step per line', null=True),
        ),
    ]
