# Generated by Django 6.0.4 on 2026-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_gymfood_ingredients_gymfood_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymfood',
            name='category',
            field=models.CharField(choices=[('high-protein', 'High Protein'), ('complex-carbs', 'Complex Carbs'), ('fruits', 'Fruits'), ('hydration', 'Hydration'), ('healthy-fats', 'Healthy Fats'), ('low-calorie', 'Low Calorie'), ('gym-snacks', 'Gym Snacks')], max_length=50),
        ),
    ]
