# Generated by Django 6.0.4 on 2026-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_gymfood_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('glow', 'Natural Glow'), ('hydration', 'Deep Hydration'), ('clearer', 'Clearer Skin'), ('aging', 'Anti-Aging'), ('firm', 'Firm & Elastic'), ('detox', 'Detox & Purify'), ('brightening', 'Brightening'), ('sensitive', 'Sensitive Skin')], max_length=20)),
                ('emoji', models.CharField(default='🌿', help_text='Single emoji to represent this food', max_length=10)),
                ('benefit_summary', models.CharField(help_text="Short one-liner e.g. 'Reduces redness & boosts glow'", max_length=200)),
                ('description', models.TextField(help_text='Full benefit description shown on the card')),
                ('key_nutrient', models.CharField(help_text='e.g. Beta-Carotene, Vitamin C, Omega-3', max_length=100)),
                ('how_to_use', models.TextField(blank=True, help_text="How to incorporate this food e.g. 'Add to smoothies daily'")),
                ('image', models.ImageField(blank=True, null=True, upload_to='skin_foods/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category (lower = first)')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
