# Generated by Django 6.0.4 on 2026-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_skinfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinfood',
            name='emoji',
        ),
    ]
