# Generated by Django 6.0.4 on 2026-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_skinfood_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('immunity', 'Immunity'), ('energy', 'Energy & Vitality'), ('gut', 'Gut Health'), ('sleep', 'Better Sleep'), ('stress', 'Stress Relief'), ('brain', 'Brain & Focus'), ('weight', 'Weight Balance'), ('hormones', 'Hormonal Balance')], max_length=20)),
                ('emoji', models.CharField(default='🌿', max_length=10)),
                ('benefit_summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('key_nutrient', models.CharField(max_length=100)),
                ('how_to_use', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wellness_foods/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
