# Generated by Django 6.0.4 on 2026-05-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_wellnessfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessfood',
            name='emoji',
        ),
    ]
