# Generated by Django 6.0.4 on 2026-05-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_wellnessfood_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComradeMealStewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('fish', 'Fish'), ('greens', 'Greens / Vegetables'), ('legumes', 'Legumes / Beans'), ('egg', 'Egg'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('low-mid', 'Low-Mid'), ('mid', 'Mid'), ('high', 'High'), ('mid-high', 'Mid-High')], default='low', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stew_options/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('ingredients', models.TextField(blank=True, help_text='Comma-separated list of ingredients')),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('recipe_steps', models.TextField(blank=True, help_text='One step per line', null=True)),
                ('comrade_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stew_options', to='core.comrademeal')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ComradeFoodStewOption',
        ),
    ]
