# Generated by Django 6.0.4 on 2026-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_comrademealstewoption_delete_comradefoodstewoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comradefood',
            name='can_combine_with',
        ),
        migrations.RemoveField(
            model_name='comradefood',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comradefood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comradefood',
            name='ingredients_needed',
        ),
        migrations.RemoveField(
            model_name='comradefood',
            name='upgrade_tip',
        ),
        migrations.AddField(
            model_name='comrademeal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner / Supper'), ('anytime', 'Anytime')], default='general', max_length=20),
            preserve_default=False,
        ),
    ]
