# Generated by Django 6.0.4 on 2026-05-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_comradefood_can_combine_with_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='comrademeal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='comrademeal',
            name='meal_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('snack', 'Snack')], default='food', max_length=10),
        ),
        migrations.AddField(
            model_name='comrademeal',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='comrade_meals', to='core.mealcategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='core.mealcategory'),
        ),
    ]
