# Generated by Django 6.0.4 on 2026-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_mealcategory_remove_comrademeal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comrademeal',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='categories',
        ),
        migrations.AddField(
            model_name='comrademeal',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more: breakfast, lunch, dinner, anytime'),
        ),
        migrations.DeleteModel(
            name='MealCategory',
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more: breakfast, lunch, dinner, anytime'),
        ),
    ]
