# Generated by Django 6.0.4 on 2026-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_comrademeal_categories_remove_dish_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('date', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'slot', 'created_at'],
            },
        ),
    ]
