# Generated by Django 6.0.4 on 2026-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_mealplanentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='comradefood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comrade_foods/'),
        ),
    ]
